### PR TITLE
 Sync Hydro to Indigo Branch - Try 2

### PR DESCRIPTION
**Pull request by davetcoleman**
Retry via cherry-pick method. Original: https://github.com/ros-planning/moveit_planners/pull/40

### CODE REVIEW

**Comment by hersh** [comment]
Travis failed.

**Comment by mikeferguson** [comment]
@hersh The travis failure is unrelated to this pull request I think -- the indigo job is still running against hydro and is failing all the time....

**Comment by davetcoleman** [comment]
Correct, travis will not succeed, but this time Github does not have any merge conflicts. This should be merged as it already exists in Hydro and we want to keep the branches synced.

**Comment by mikeferguson** [comment]
And from the looks of it, travis doesn't support 14.04 yet? Thus we can't do tests on Indigo?

**Comment by davetcoleman** [comment]
Travis needs to be disregarded for all Indigo PRs until Travis is upgraded to 14.04 (its still 12.04)

**Pull request merged**
