### PR TITLE
fix compile error on Indigo

### PR DESCRIPTION
**Pull request by astumpf**
This patch will fix compiling issue related to Indigo (see http://wiki.ros.org/indigo/Migration). Obviously this should happen in a new indigo-devel branch.

### CODE REVIEW

**Comment by mikeferguson** [comment]
This should fix #34 -- however, I think this can only be used on indigo -- so either we have to do an ifdef based on ROS version, or branch for indigo-devel. @tfoote -- does that sound right?

**Comment by astumpf** [comment]
Yep, that's right. In my opinion a new indigo-devel branch is the more "common" solution.

**Comment by mikeferguson** [comment]
I concur that branching is probably the best approach

**Comment by sachinchitta** [comment]
@astumpf could you please close this PR do a new PR against the indigo-devel branch I just created?

Thanks for the contribution!

**Comment by astumpf** [comment]
Done

**Pull request closed without merging**
