### PR TITLE
Sync Hydro to Indigo Branch

### PR DESCRIPTION
**Pull request by davetcoleman**

### CODE REVIEW

**Comment by davetcoleman** [comment]
Merging https://github.com/ros-planning/moveit_planners/pull/38 and https://github.com/ros-planning/moveit_planners/pull/39

Is it bad that this PR also merges the Changelog changes? They should be the same anyway, right? Does the indigo branch need to be released still?

**Comment by hersh** [comment]
Github tells me there are merge conflicts. Can you resolve them?

The Changelog should reflect the release history.  If there is ambiguity because of hydro/indigo, just sort of use your best judgement and prefer including rather than excluding information.

**Comment by davetcoleman** [comment]
The merge conflict is because the hydro debian/release is only on version `0.5.6-0` but the indigo debian/release is on version `0.6.6-0`. It seems to me if we are going to keep the branches having the same code they also need to have the same release number. Otherwise package.xml and CHANGELOG.rst are not going to be the same. Can we release a new version of the hydro branch that 'catches it up to' the indigo branch?

**Comment by mikeferguson** [comment]
@davetcoleman The release numbers have to be different, as they are different codebases (due to build changes). The correct thing to do here is probably to cherry-pick the commits from indigo back to hydro and not use the changelog/package.xml ones.

**Comment by hersh** [comment]
I agree with Mike, once the code diverges you have to cherry-pick.

**Comment by mikeferguson** [comment]
Alternatively,  you could dual-pull-request each of the PRs -- but I think the cherry-picking is less work

**Comment by davetcoleman** [comment]
A little more work :-/
New PR: https://github.com/ros-planning/moveit_planners/pull/42

**Pull request closed without merging**
