### PR TITLE
Installation instructions for OMPL with catkin

### PR DESCRIPTION
**Pull request by davetcoleman**
I also moved documentation configuration to the /doc subfolder

### CODE REVIEW

**Comment by v4hn** [comment]
These docs do not generate a index.html , but a index-msg.html that links to index.html.
Why is that?

**Comment by davetcoleman** [comment]
I believe there is an autogenerated index file, but it didn't look very useful / wasn't setup correctly. For now we just are using the tutorial.html linked from the moveit website. The index-msg stuff is default rosdoc-lite, don't fully understand it. Feel free to improve in different PR

**Comment by v4hn** [comment]
ok, the tutorial.html looks good.
I'm not sure optimization configuration and ompl source install belong on the same html page,
but this short snippet is probably not worth having a page on its own,
so merging.

Should this also be picked to the other branches or is there any reason not to?

**Comment by davetcoleman** [comment]
Yes it should be cherry-picked, I can do that now

**Pull request merged**
